### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by lingya** [gmmstrive/flink-connector-clickhouse#1]
请问下，
1，如果不用 zeppelin  ， 这个仓库
flink-connector-clickhouse可以使用吗 ？例如我直接在sql-client里面

2，flink.execution.jars /Users/lucas/IdeaProjects/microi/flink-microi-conn/clickhouse/target/clickhouse-1.0-SNAPSHOT.jar

如果不用 zeppelin，flink.execution.jars  这个参数是否可以用 -yj ？

**Comment by gmmstrive** [comment]
你好，
	我并没有尝试 sql-client 直接使用，但是我继承 flink 官网建议的使用方式，我觉得应该是适用的， 直接加载在 flink job 运行环境中会自动注册的，现在 zeppelin 开箱即用，建议可以使用一下，

**Comment by lingya** [comment]
谢谢，我在sql-client中试一下，学习下 zeppelin 


> 你好，
> 	我并没有尝试 sql-client 直接使用，但是我继承 flink 官网建议的使用方式，我觉得应该是适用的， 直接加载在 flink job 运行环境中会自动注册的，现在 zeppelin 开箱即用，建议可以使用一下，
> …
