### ISSUE TITLE
batch insert 

### ISSUE THREAD

**Issue by lingya** [gmmstrive/flink-connector-clickhouse#4]
Whether batches are supported   this method  

stmt.write().table(jdbcOptions.getTableName()).data(new ByteArrayInputStream(serialize), ClickHouseFormat.JSONEachRow)
                .addDbParam(ClickHouseQueryParam.MAX_PARALLEL_REPLICAS, MAX_PARALLEL_REPLICAS_VALUE).send();

How's that speed of insert ？

**Comment by gmmstrive** [comment]
It is only used on a small scale at present, you can test it according to your actual situation, it is not very difficult

**Comment by lingya** [comment]
ok
