### ISSUE TITLE
建表的时候，指定的format起到什么作用呢？

### ISSUE THREAD

**Issue by ltylty** [gmmstrive/flink-connector-clickhouse#5]
DROP TABLE IF EXISTS ch;
CREATE TABLE ch (
    id String,
    name String,
    age String,
    create_date Date
) WITH (
    'connector' = 'clickhouse',
    'url' = 'jdbc:clickhouse://172.16.8.164:8123,172.16.8.165:8123,172.16.8.166:8123/dc2', -- 可配置集群地址，写入时随机选择连接写入，不会一直使用一个连接写入
    'table-name' = 'user_name',
    'username' = 'default',
    'password' = '',
    'format' = 'json'
);

这个语句中的'format' = 'json'起什么作用呢？

**Comment by gmmstrive** [comment]
数据是 json 格式， {“name”:”xxx”} ，你可以看下 flink sql 官方文档里面的 format 的用法，这里仅支持 json
